名称：
	throw() - 强制在一个物件中产生错误。
语法：
	void throw(mixed);

	无传回值 throw( 混合 );
用法：
	throw() 可以在闭合的 catch() 叙述内〈译注：即 catch() {} 里面〉送
	出指定的任意值。如果你只是想产生一个普通的错误，请参考 error()，因
	为 error() 产生的错误如果没被抓到，它造成的结果比较好。程式的控制
	权会立刻交到 catch() 函式手上，而 catch() 叙述的值就是 throw() 送
	出的值。
参考：
	catch, error
作者：
	Tim Hollebeek  Beek@ZorkMUD, Lima Bean, IdeaExchange, and elsewhere
翻译：
	spock@muds.net		2000.May.27.	v22 版
